spring.application.name=AutoLoc

# Connexion à la base de données (base renommée : autoloc_db -> autoloc_assoc_db)
spring.datasource.url=jdbc:mysql://localhost:3306/autoloc_assoc_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8089

# Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.tn.esprit.autoloc=INFO
